[package]
name = "zippyst"
version = "0.1.0"
authors = ["Scotow <contact@scotow.com>"]
edition = "2018"

[dependencies]
curl = "0.4.25"
scraper = "0.11.0"
url = "2.1.0"
regex = "1"
percent-encoding = "2.1.0"
minicalc = { git = "https://github.com/irevoire/minicalc" }