name: Update fork and build Docker image

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.name "${{ secrets.USER_NAME }}"
        git config --global user.email "${{ secrets.USER_EMAIL }}"

    - name: Fetch upstream changes
      uses: pengsrc/auto-merge-action@v1
      with:
        repo-token: ${{ secrets.TOKEN }}
        upstream: upstream
        upstream-branch: main
        target-branch: main

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nunodxxd/zippyst:latest
